# THIS IS CURRENTLY (10/2023) NOT IN USE!

- platform: gree
  port: 7000
  target_temp_step: 1
#  temp_sensor: <entity id of the EXTERNAL temperature sensor. For example: sensor.bedroom_temperature>
#  encryption_key: <OPTIONAL: custom encryption key>
#  lights: <OPTIONAL: input_boolean to switch AC lights mode on/off. For example: input_boolean.first_ac_lights>
#  xfan: <OPTIONAL: input_boolean to switch AC xfan mode on/off. For example: input_boolean.first_ac_xfan>
#  health: <OPTIONAL: input_boolean used to switch the Health option on/off of your first AC. For example: input_boolean.first_ac_health>
#  sleep: <OPTIONAL: input_boolean to switch AC sleep mode on/off. For example: input_boolean.first_ac_sleep>
#  powersave: <OPTIONAL: input_boolean to switch AC powersave mode on/off. For example: input_boolean.first_ac_powersave>
#  eightdegheat: <OPTIONAL: input_boolean used to switch 8 degree heating on/off on your first AC>
#  air: <OPTIONAL: input_boolean used to switch air/scavenging on/off on your first AC>

#  target_temp_step: 1…