# This is here for a reason - it includes stuff like mobile app configuration already.
default_config:

# This includes packages such as "landroids.yaml" in the /packages folder
homeassistant:
  packages: !include_dir_named packages

group: !include groups.yaml
lovelace: !include lovelace.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml

# Add Gree Climate (REMOVED 20.10.2023 to replace with core GREE plugin)
#climate: !include climate.yaml

# Change database location:
# https://www.home-assistant.io/integrations/recorder/
recorder:
  db_url: sqlite:////db/home-assistant_v2.db

# About templates and sensors in general:
# https://www.home-assistant.io/integrations/template/

# Discovery of devices automatically if supported
discovery:

stream:
ffmpeg:

#area: !include areas.yaml

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info


# Simple scheduled countdowns
garbage_collection:
  sensors:
  - name: garbage
    frequency: 'every-n-weeks'
    period: 2
    collection_days: 
    - "tue"
    first_week: 1 # This might change year-on-year


# Temperature, hygro, door etc sensors
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  sensors: [temperature, humidity, power, current, voltage, rssi]
  
# Ecovacs Deebot N79S
ecovacs:
  username: !secret ecovacs_username
  password: !secret ecovacs_password
  country: fi
  continent: eu

# NORDPOOL ELECTRICITY PRICES: https://github.com/custom-components/nordpool
# (See the rest of the Nordpool stuff in sensors.yaml)
nordpool: