# This is here for a reason - it includes stuff like mobile app configuration already.
default_config:

# This includes packages such as "landroids.yaml" in the /packages folder
homeassistant:
  packages: !include_dir_named packages

group: !include groups.yaml
lovelace: !include lovelace.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
camera: !include cameras.yaml

# Change database location:
# https://www.home-assistant.io/integrations/recorder/
recorder:
  db_url: sqlite:////db/home-assistant_v2.db


# Discovery of devices automatically if supported
discovery:

stream:
ffmpeg:

logger:
  default: info

  
# Ecovacs Deebot N79S
ecovacs:
  username: !secret ecovacs_username
  password: !secret ecovacs_password
  country: fi
  continent: eu
